### ISSUE TITLE
Font and wake up lights?

### ISSUE THREAD

**Issue by centaurclock** [vikonix/O-Clock#1]
![SI859105](https://user-images.githubusercontent.com/67684214/90563720-2596a980-e19c-11ea-88ab-a5a3040a34c2.JPG)
Hi, I'd like to change the temp/pressure display so that it will display only temp or humidity, same size as the main font in the same place, I also want to add some LED lights to the alarm as a sunrise simulator, would this need to be 1 coming on after the other or could it go from low to high? Any help would be appreciated. Lee.

**Comment by vikonix** [comment]
Hi Lee.
The idea with big digits for temp/pressure is clear for me. Only question can you draw in any graphic editor how does you see it? This is only digits or some additional sign?

About "sunrise" it's not clear. Is it means that you want to see some light effect during alarm? For example it's light changing from low to high and down?

Valeriy

**Comment by centaurclock** [comment]
Hi Valeriy,
The sunrise function would be like a sunrise or dawn simulator alarm clock, where over half an hour a light on the clock would go from compleatly off (low) to full on (high) to mimic sunrise, I don't know if a single LED would work for that as they are not very good at very low power which is why I was wondering if it would need a bank of  perhaps 10 with one coming on every three minutes, they would not be part of the dot matrix display but perhaps seperate. 
![tenor](https://user-images.githubusercontent.com/67684214/91221963-66e80580-e716-11ea-888f-77ed143690df.gif)
![celsius](https://user-images.githubusercontent.com/67684214/91222540-40769a00-e717-11ea-81ab-72b235ab5bf8.jpg)
![humidity](https://user-images.githubusercontent.com/67684214/91222542-41a7c700-e717-11ea-9b00-39ae99cb543d.jpg)

What I'm ultimatly trying to build is a sort of nixie lamp clock, but as I can't afford the real tubes I was going to use your clock as the base, box it into a wooden houseing and use some plastic tubes cut in half at the front to make it look like nixie tubes, which is why I can't use the smaller font as it won't match where the matrix will be vissible.
![SI859106](https://user-images.githubusercontent.com/67684214/91222968-d3afcf80-e717-11ea-92fa-692382846a8d.JPG)

**Comment by vikonix** [comment]
Hi Lee,
I have created "develop" branch for nixie emulation. I changed showing temp with big digits. Is it what you expected?

**Comment by centaurclock** [comment]
Thanks, thats made it show now. I was hoping to split the data, so at 15s it show temp and 45 it shows humidity, I don't know if thats possible with the BME280 sensor is it? or does the data come together so it can't be seperated?

**Comment by vikonix** [comment]
It's not problem to separate them. What also you want to see at 30s ?

**Comment by centaurclock** [comment]
Probably nothing, although I've been running it with them together and kinda like it like that as I can see both at the same time. I changed the seperator for those to a solid line so its clear its not the normal time display at a glance. Where are the melody files? are they in one of the libararies? I was trying to find them to take a look at adding a diferent sound and assumed they were actualy in the code in binary or something but I cant find them at the moment?

**Comment by vikonix** [comment]
Melody you can see in oclock.cpp:96
// alarm melody in RTTTL format
You can find them with "nokia ringtone rtttl"

**Comment by vikonix** [comment]
https://en.wikipedia.org/wiki/Ring_Tone_Transfer_Language

**Comment by centaurclock** [comment]
ah, thankyou.

**Comment by centaurclock** [comment]
Sorry to keep bothering you, I've got the buzzing you said about, do you have a diagram of where the capacitors go? I'm not sure where I'm supposed to add them in. 
Kindest regards,
Lee.

**Comment by vikonix** [comment]
I add simple power filter chematic
https://github.com/vikonix/O-Clock/blob/master/docs/Schematic_power%20filter_2020-09-13_20-39-50.pdf

**Comment by centaurclock** [comment]
Thanks, that make it clear now.

**Comment by centaurclock** [comment]
Thanks, I added the power filter in but still got some hiss, but I solved it by adding an LED parralel to the buzzer.

**Comment by ooomakon** [comment]
Здравствуйте,а как можно сделать отображение давления в мм.рт?Спасибо.

**Comment by vikonix** [comment]
Добрый вечер.

main.cpp:41
//#define PRESSURE_IN_MM

нужно раскомментировать эту строчку

**Comment by ooomakon** [comment]
сделал, также осталось

**Comment by vikonix** [comment]
Сейчас только что проверил. Нормально показывает в мм.
